### PR TITLE
Support new RATELIMIT features

### LINKED ISSUE #149: Support new RATELIMIT features
AUTH_RATELIMIT is now AUTH_RATELIMIT_IP and should be renamed.
AUTH_RATELIMIT_SUBNET is replaced by AUTH_RATELIMIT_EXEMPTION

The new chart should fail if any of the old settings are in use.

The following new settings should be added: AUTH_RATELIMIT_USER, AUTH_RATELIMIT_EXEMPTION_LENGTH

### PR DESCRIPTION
**Pull request by fischerscode**
This PR adds support for new RATELIMIT features introduced in 1.9.

I'm pretty new to developing helm charts, so I don't know if this is the best way to do it.
Feel free to criticize :-D

> The new chart should fail if any of the old settings are in use.

This is not done:
1. I don't know how to make the chart fail if a value is set.
2. I don't think it's is better to keep thinks simple and instead document the "changed" behavior.

close #149

### CODE REVIEW

**Comment by fischerscode** [comment]
When testing to change `authRatelimitIP`, it might not work, since the feature seems to be broken. (https://github.com/Mailu/Mailu/issues/2283)

**Comment by nextgens** [comment]
Bump mailuVersion; It's been fixed

**Comment by micw** [comment]
Great PR!
It seems that mailu is curerntly not limited since AUTH_RATELIMIT is not supported anymore. Shoud we default to a much higher (or maybe unlimited) to not break existing deployments?

**Comment by micw** [comment]
I have rebased and merged it locally, adding a check for the outdated option.

**Pull request closed without merging**
