### PR TITLE
Refactor Helm Chart

### PR DESCRIPTION
**Pull request by fastlorenzo**
This is a full refactor of the Helm Chart to make it more customizable and easier to maintain.
Most changes are based on what is done on [Bitnami Helm Charts](https://github.com/bitnami/charts/)

### CODE REVIEW

**Comment by Riukotashi** [comment]
Any news on when it will be implemented, I'm really interested of feature describe on #141.
I any help is needed I can give a try !

Thanks for your work

**Comment by fastlorenzo** [comment]
> Any news on when it will be implemented ? I'm really interested of feature describe on #141. I any help is needed I can give a try !
> 
> Thanks for your work

@Riukotashi The refactor is normally complete, but we need some people to test it both for new or existing install.
For existing install, we still need to create an upgrade guide as some things changed.

You can try out the refactored version by using this temporary Helm repo: https://fastlorenzo.github.io/helm-charts-1/

Latest version is `mailu-1.0.0-beta.4`.

**Comment by fastlorenzo** [comment]
Released [`mailu-1.0.0-beta.5`](https://github.com/fastlorenzo/helm-charts-1/releases/tag/mailu-1.0.0-beta.5) (via `https://fastlorenzo.github.io/helm-charts-1/` helm repo)

**Comment by psych0d0g** [comment]
installed 1.0.0-beta.27 on my k8s, and i somehow ended up with a "webmail" and a "roundcube" pod, whereas the webmail container only knows the tags "latest", "master" and no version specific ones...

```
NAME                                  READY   STATUS    RESTARTS      AGE
pod/mailu-admin-659ddddc69-prn2r      1/1     Running   0             10m
pod/mailu-clamav-0                    1/1     Running   0             34m
pod/mailu-dovecot-5c988b8d4b-hv8gt    1/1     Running   0             10m
pod/mailu-front-d49d4f56b-st9b9       1/1     Running   0             11m
pod/mailu-postfix-65c4d484fb-t9fx2    1/1     Running   1 (33s ago)   66s
pod/mailu-redis-master-0              1/1     Running   0             34m
pod/mailu-roundcube-9576c5d7c-6xxfg   1/1     Running   0             34m
pod/mailu-rspamd-6cf8b898d7-c2c4x     1/1     Running   0             11m
pod/mailu-webmail-697699b598-2ft8l    1/1     Running   0             110s

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                             AGE
service/mailu-admin             ClusterIP   10.104.153.145   <none>        80/TCP                                                                              34m
service/mailu-clamav            ClusterIP   10.106.26.4      <none>        3310/TCP                                                                            34m
service/mailu-clamav-headless   ClusterIP   None             <none>        3310/TCP                                                                            34m
service/mailu-dovecot           ClusterIP   10.111.25.8      <none>        2102/TCP,2525/TCP,143/TCP,110/TCP,4190/TCP                                          34m
service/mailu-front             ClusterIP   10.103.26.182    <none>        110/TCP,995/TCP,143/TCP,993/TCP,25/TCP,465/TCP,587/TCP,10025/TCP,10143/TCP,80/TCP   34m
service/mailu-postfix           ClusterIP   10.106.26.197    <none>        25/TCP,465/TCP,587/TCP,10025/TCP                                                    34m
service/mailu-redis-headless    ClusterIP   None             <none>        6379/TCP                                                                            34m
service/mailu-redis-master      ClusterIP   10.108.219.218   <none>        6379/TCP                                                                            34m
service/mailu-roundcube         ClusterIP   10.101.255.230   <none>        80/TCP                                                                              34m
service/mailu-rspamd            ClusterIP   10.96.31.83      <none>        11332/TCP,11334/TCP                                                                 34m
service/mailu-webmail           ClusterIP   10.104.159.177   <none>        80/TCP                                                                              12m
```

my values.yaml can be found within my fluxCD helmrelease.yaml: https://gitlab.com/psych0d0g/k8s_cluster/-/blob/main/deployments/mailserver/mailu/helm-deployment/helmrelease.yaml


i am not sure if this is intentional?
especially since my ingress complains about backend not being reachable as long as the webmail pod is not running, despite the roundcube pod being fine :)

**Comment by fastlorenzo** [comment]
> installed 1.0.0-beta.27 on my k8s, and i somehow ended up with a "webmail" and a "roundcube" pod, whereas the webmail container only knows the tags "latest", "master" and no version specific ones...
> 
> ```
> NAME                                  READY   STATUS    RESTARTS      AGE
> pod/mailu-admin-659ddddc69-prn2r      1/1     Running   0             10m
> pod/mailu-clamav-0                    1/1     Running   0             34m
> pod/mailu-dovecot-5c988b8d4b-hv8gt    1/1     Running   0             10m
> pod/mailu-front-d49d4f56b-st9b9       1/1     Running   0             11m
> pod/mailu-postfix-65c4d484fb-t9fx2    1/1     Running   1 (33s ago)   66s
> pod/mailu-redis-master-0              1/1     Running   0             34m
> pod/mailu-roundcube-9576c5d7c-6xxfg   1/1     Running   0             34m
> pod/mailu-rspamd-6cf8b898d7-c2c4x     1/1     Running   0             11m
> pod/mailu-webmail-697699b598-2ft8l    1/1     Running   0             110s
> 
> NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                             AGE
> service/mailu-admin             ClusterIP   10.104.153.145   <none>        80/TCP                                                                              34m
> service/mailu-clamav            ClusterIP   10.106.26.4      <none>        3310/TCP                                                                            34m
> service/mailu-clamav-headless   ClusterIP   None             <none>        3310/TCP                                                                            34m
> service/mailu-dovecot           ClusterIP   10.111.25.8      <none>        2102/TCP,2525/TCP,143/TCP,110/TCP,4190/TCP                                          34m
> service/mailu-front             ClusterIP   10.103.26.182    <none>        110/TCP,995/TCP,143/TCP,993/TCP,25/TCP,465/TCP,587/TCP,10025/TCP,10143/TCP,80/TCP   34m
> service/mailu-postfix           ClusterIP   10.106.26.197    <none>        25/TCP,465/TCP,587/TCP,10025/TCP                                                    34m
> service/mailu-redis-headless    ClusterIP   None             <none>        6379/TCP                                                                            34m
> service/mailu-redis-master      ClusterIP   10.108.219.218   <none>        6379/TCP                                                                            34m
> service/mailu-roundcube         ClusterIP   10.101.255.230   <none>        80/TCP                                                                              34m
> service/mailu-rspamd            ClusterIP   10.96.31.83      <none>        11332/TCP,11334/TCP                                                                 34m
> service/mailu-webmail           ClusterIP   10.104.159.177   <none>        80/TCP                                                                              12m
> ```
> 
> my values.yaml can be found within my fluxCD helmrelease.yaml: https://gitlab.com/psych0d0g/k8s_cluster/-/blob/main/deployments/mailserver/mailu/helm-deployment/helmrelease.yaml
> 
> 
> i am not sure if this is intentional?
> especially since my ingress complains about backend not being reachable as long as the webmail pod is not running, despite the roundcube pod being fine :)
> 
> 
> okay, figured it out myself, you just recently changed to the new webmail container that includes roundcube AND snappymail, but unfortunately does indeed not yet has any tags on dockerhub

Thanks for the feedback, indeed I've adapted the chart to support the new changes in Mailu, which moved the roundcube container to webmail; the fact you have both might be related to the helm upgrade that was not complete since, as you've pointed out, there is not tag yet on docker hub for the webmail container.
Hopefully the next mailu release will be done soon enough, once it is done we'll work merging this PR into the official mailu helm repo ;)

Don't hesitate if you find anything / have some ideas for improvement of the chart!

**Pull request merged**
