### PR TITLE
add fetchmail deployment

### PR DESCRIPTION
**Pull request by yeoldegrove**
This adds fetchmail support to the chart.
It is disabled by default-
Included are also parameters to tune the `FETCHMAIL_DELAY`.

### CODE REVIEW

**Comment by elmanytas** [comment]
A little question, I'm new in mailu and I'm not familiar with the architecture ... why are you using front to send mail instead of use postfix service?

**Comment by elmanytas** [comment]
Now I see a problem: the fetchmail container does not support environment var LOG_LEVEL.
It uses the environment var DEBUG so LOG_LEVEL will be ignored: https://github.com/Mailu/Mailu/blob/master/optional/fetchmail/fetchmail.py#L98

**Comment by yeoldegrove** [comment]
> Now I see a problem: the fetchmail container does not support environment var LOG_LEVEL.
> It uses the environment var DEBUG so LOG_LEVEL will be ignored: https://github.com/Mailu/Mailu/blob/master/optional/fetchmail/fetchmail.py#L98

You are absolutely right.
Fixed this in 02dc0176ea6b3f60bdfafbab888a0b127538929f.

**Comment by yeoldegrove** [comment]
> A little question, I'm new in mailu and I'm not familiar with the architecture ... why are you using front to send mail instead of use postfix service?

I used the `mailu-front` service, as the pod behind it is a reverse proxy for all the services. It will forward the request to the `admin` pod which than decides if TLS or auth has to be used.

"Works for me" ... Using postfix directly "could/should" also work.

**Comment by micw** [comment]
Thank you for that PR. Since fetchmail is always visible in the UI, would it make sense to enable it by default (so that users can expect it to work by default)?

**Comment by KeepMasterBranch** [comment]
This PR had been ready for merging for 5 months

Who's need what to get this merged?

**Comment by mjdazz** [comment]
I'd also love to see this merged. I do agree that having it enabled by default makes sense.
Any chance this might be merged soon @micw ? :)

**Comment by micw** [comment]
My apologies not to find the time till now

**Comment by mjdazz** [comment]
Thank you for your quick response!
However, I don't see the new version on the GitHub pages. I'm not familiar with Travis, does the build still need to be triggered?

**Comment by micw** [comment]
Reason is that travis-ci.org has closed it's free service, so no builds are performed anymore

**Comment by micw** [comment]
Builds fixed with #97

**Pull request merged**
