### PR TITLE
Add possibility to configure REST API

### PR DESCRIPTION
**Pull request by Deltachaos**
Currently the Helm Charts have no possibility to enable the REST API in current Mailu release. This PR adds the functionality.

### CODE REVIEW

**Comment by fastlorenzo** [comment]
Thank you for the PR, I have not tested the API yet; I'll take some time to review this

**Comment by Deltachaos** [comment]
any updates on this?

**Comment by KhangLama** [comment]
any update, I really need to use api on k8s

**Comment by dosielczak** [comment]
is there any progress here? Having this would be very useful to us

**Comment by fastlorenzo** [comment]
Thank you for the PR, feature added in #358

**Pull request closed without merging**
