### PR TITLE
feat(proxy): add PROXY_PROTOCOL parameter

### PR DESCRIPTION
**Pull request by Sh4kE**
Adds the possibility to define proxy protocol parameter

### CODE REVIEW

**Comment by nextgens** [comment]
I see that we've missed it in our docs, but "all-but-http" is now valid too on master

**Comment by Sh4kE** [comment]
Ahh the haven't updated their docs yet. I missed that.

**Comment by Sh4kE** [comment]
Hmm are you sure about that?
This is the PR which introduced the parameter and I can't seem to find that value:
https://github.com/Mailu/Mailu/pull/2717/files#diff-68a31565c7f34fbe6ac80bbc0b4287ee3711fa615ce5b973c1f83f285d0d28fa

**Comment by nextgens** [comment]
https://github.com/Mailu/Mailu/pull/2903/files

But that's only valid for master... and arguably the chart doesn't target that

**Comment by fastlorenzo** [comment]
Fixed in #354 , thanks for the PR though

**Pull request closed without merging**
