### PR TITLE
Allow to use existing PVC

### PR DESCRIPTION
**Pull request by soriyath**
@micw I'm opening this one so that my master branch reflects the upstream's master.

### CODE REVIEW

**Comment by soriyath** [comment]
Hello All,

I've made some changes so that I can install the helm chart for mailu on my Rancher v2.3.4 environment.

In that regard, I have:

added a few new parameters to the persistence parameters;
kept the hostingPath persistence type per default;
added the mailu.claimName convenience variable as an indirection to the PVC (defaulting to mailu-storage as per before);
updated the README.md file with some more context.
Please note, in order to install it on my server, I've created a helm repo on my Github page.
You will see the artifact and the index.yaml, as well as some config files for GitHub page on the PR.
I can either remove them or we can delete them after the merge. I'm keeping it like this as there probably will be review comments for modifications.

Best Regards,

Soriyath

**Comment by soriyath** [comment]
> Please remove the binary files from the built charts from the PR
> 
> We have 3 situations to handle:
> hostpath: create PV and PVC that uses this PV
> managed PVs: create PVC but no PV
> (new) existing claim: use existing claim name, create neither PV nor PVC
> 
> Please edit pvc.yaml accordingly, I added comments there too

This case is not yet managed:
- managed PVs: create PVC but no PV

**Comment by soriyath** [comment]
@micw Thank you for the feedback.

**Comment by micw** [comment]
Thank you for contributing

**Comment by soriyath** [comment]
It's my first open source contribution 😄

**Comment by micw** [comment]
Well done :-)

**Pull request merged**
