### PR TITLE
Add RELAYHOST support

### PR DESCRIPTION
**Pull request by Grennith**
Hi,
Mailu supports setting a RELAYHOST along with login credentials via the environment variables.
This patch/PR adds that basic usage to the Helm-chart

### CODE REVIEW

**Comment by micw** [comment]
Thank you. I'm not 100% happy with the variable naming (external_relay.relayhost, external_relay.relayuser, external_relay.relaypassword). How about relay.host, relay.user, relay.password (or external_relay.host, external_relay.user, external_relay.password)?

Please also add it to the README.md (ideally with a short section "external relay"). I know the READMY it is quite incomplete but i'd like to have it updated at least for new stuff.

**Comment by unixfox** [comment]
@Grennith any updates on this PR?

**Comment by Grennith** [comment]
Sorry, was pretty busy the last couple of days.
I have no issue with renaming the keys in external_relay (I do not like the naming I came up with either) and putting up a brief doc.

However, I also stumbled upon an issue which would require upstream changes tho.
Relayhost as is can be set without an issue. SSL/TLS cannot be set as is (for certain relayhosts I guess?) due to postfix configuration arguments that are not yet considered to be configurable in upstream Mailu.
Namely, my old manual postfix setup required 
`smtp_tls_security_level = encrypted` (mailu runs `may` by default)
and 2 more args not present in the main.cf of mailu.
So the README would _probably_ need to tell people to use STARTTLS as a preferred way to relay mails. I could not get SSL/TLS working without fiddling around in the main.cf of the pod - which just gets overwritten obviously (personally, I'd kinda love the main.cf to be stored on persistent storage somehow).

**Comment by micw** [comment]
> What about external_relay.host, external_relay.username, external_relay.password?

Sounds good

> I could not get SSL/TLS working without fiddling around in the main.cf

Is smtp_tls_security_level the only thing you had to change?

**Comment by micw** [comment]
Let's wait for https://github.com/Mailu/Mailu/pull/1478 to get merged.

**Comment by Grennith** [comment]
> Is smtp_tls_security_level the only thing you had to change?

Nope, it was 2 additional args - 2 of the ones below, I can try to replicate it the next couple of days. 
`smtpd_sasl_auth_enable = yes
smtp_sasl_auth_enable = yes
smtp_use_tls = yes
smtpd_use_tls = yes
smtp_tls_wrappermode = yes`

**Pull request merged**
